name: wilksy
favicon: null
layout_spectrum: 0.8521061709616333
typography_spectrum: 0.38648385740816593
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2881239883136004
  lightness: 0.8597544508520514
  saturation: 0.1314842002466321
  rhythmicContrast: 0.5860341938678175
purpose: []
